### ISSUE TITLE
GPU support for container application deployed on edgenode in On-Premises IAC mode.

### ISSUE THREAD

**Issue by ashishsaxenahsc** [open-ness/edgecontroller#19]
Hi Openness team,

We have deployed Openness release 19.12 on our setup in On-Premises IAC mode.
We are trying to deploy our application as a container on the edge-node .That application container would be required to run in privileged  mode and need gpu access.

Following parameters are required to run the container from the command line:

docker run --net host --gpus all -it --shm-size=1g --env DISPLAY=$DISPLAY --privileged --volume="$HOME/.Xauthority:/root/.Xauthority:rw" app_container

Is there any way using which we can provide the above mentioned parameters to our application running on the edge-node.

Thanks and Regards,
Ashish

**Comment by krishnajs** [comment]
@ashishsaxenahsc in Kubernetes mode you can use config maps or entry points to provide such parameters to applications in the container. In OnPremises mode we are planning to support passing environment variables in the upcoming releases which can be used to achieve the same.
