### ISSUE TITLE
How to check the initial password

### ISSUE THREAD

**Issue by w910820618** [open-ness/edgecontroller#3]
I have compiled it and can enter the controller's page, but I don't know how to check the initial password.

**Comment by asilvr** [comment]
You can edit the admin user password by changing it in your .env file (the variable is `CCE_ADMIN_PASSWORD`): https://github.com/otcshare/edgecontroller/blob/master/.env

Please be sure to check out the README, especially the Quick Start and Usage sections to become familiar with how to configure it: https://github.com/otcshare/edgecontroller/blob/master/README.md

**Comment by w910820618** [comment]
ok,thanks
