### ISSUE TITLE
Error working with kubectl command

### ISSUE THREAD

**Issue by JeevanCK7** [open-ness/edgecontroller#30]
I have completed bringing up controller and edge node.  While I'm trying to work with kubectl command. I'm getting the below error.
# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Unable to connect to the server: proxyconnect tcp: dial tcp: lookup proxy.example.org on 172.16.2.31:53: no such host

**Comment by amr-mokhtar** [comment]
Hi @JeevanCK7 , You need to configure your proxy settings according to https://github.com/open-ness/specs/blob/master/doc/getting-started/network-edge/controller-edge-node-setup.md#setting-proxy -- If your network uses proxy, you need to replace `proxy.example.com` with your actual proxy server.

**Comment by JeevanCK7** [comment]
Hi @amr-mokhtar how should I configure if our network doesnot make use of proxy server?

**Comment by JeevanCK7** [comment]
@amr-mokhtar proxy_os_enable is set to false. deploy_ne.sh script for controller and edge node is successful. But when I'm trying to execute kubectl command. I'm facing error like this. My network doesnot use proxy server.
<img width="960" alt="kubectl_version_error" src="https://user-images.githubusercontent.com/64581852/83113374-34157d80-a0e5-11ea-8f90-d4b11d8917e8.png">

**Comment by amr-mokhtar** [comment]
Did you have proxy_os_enable set to false since the beginning? If you change it, you need to clean and re-deploy.
Also, can you try to clear the proxy values like `proxy_os_http: ""`.
