### ISSUE TITLE
Network Edge mode how to retrieve kubernetes information

### ISSUE THREAD

**Issue by saberlilydian** [open-ness/edgecontroller#4]
When Network Edge mode is used, below kubernetes information are required. Could you please give a guide on how to retrieve these information.

CCE_K8S_MASTER_HOST=<KUBERNETES-MASTER-HOST-ADDRESS>
CCE_K8S_MASTER_USER=<KUBERNETES-DEFAULT_USER>
CCE_K8S_API_PATH=<KUBERNETES-API-PATH>
CCE_K8S_CLIENT_CA_PATH=/your/path/ca.pem
CCE_K8S_CLIENT_CERT_PATH=/your/path/cert.pem
CCE_K8S_CLIENT_KEY_PATH=/your/path/key.pem

**Comment by anurag-ness** [comment]
Hi Saberlilydian, 19.12 release experience kit automates the installation. Did you check?

**Comment by amr-mokhtar** [comment]
Hi @saberlilydian, Are you okay to close this issue? As was commented by @anurag-ness, installation has been fully automated by [openness-experience-kits](https://github.com/open-ness/openness-experience-kits). Please let us know if you have any further issues.
