### ISSUE TITLE
Premise is not singular or Premises. Documentation errors

### ISSUE THREAD

**Issue by larryjhorner** [open-ness/edgecontroller#7]
In the README and other documentation the word 'premise' is used where 'premises' should be used.
The former is not the singular of the latter, a very common but easily corrected mistake.
According to many popular dictionaries:

Premise
noun
1. LOGIC
a previous statement or proposition from which another is inferred or follows as a conclusion.
"if the premise is true, then the conclusion must be true"
verb
2. base an argument, theory, or undertaking on.
"the reforms were premised on our findings"

Premises
noun
3. a house or building, together with its land and outbuildings, occupied by a business or considered in an official context.
"business premises"

For example:
OpenNESS supports Network Edge and On-Premise edge deployment. For details of these two deployment model please refer to the OpenNESS architecture specification.

Should be:
OpenNESS supports Network Edge and On-Premises edge deployment. For details of these two deployment model please refer to the OpenNESS architecture specification.

it's even in the training material where it is stated incorrectly.

BR,

**Comment by amr-mokhtar** [comment]
Hi @larryjhorner, Thanks for your feedback. This has been fixed all over OpenNESS docs as of 19.12 release.
