### ISSUE TITLE
Edge Controller can not find the interfaces of Edge Node?

### ISSUE THREAD

**Issue by hjwoohakimwhj** [open-ness/edgecontroller#8]
Hi. thanks your guides, I have installed openness controller and edge node successfully. When I put the serial of edge node to the controller, it seems all fine. However, when I check the interfaces of edge node, there is a "500 internal server error". Could you please tell me how to fix it?
Something that I feel confused:
1. in edgecontroller/grpc/server.go:103-104
    authpb and evapb register services, but elabp does not register services
2. in edgecontroller/pb/ela/ela.pb.go:1387-1389
    function RegisterInterfaceServiceServer register the interface service in grpc server. However, there is no xx.go using this function except /test/node/grpc/node.go. Could you please tell me where ela register interface service? Because, according to the logs " error retrieving all network interfaces: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing context deadline exceeded", it seems grpc client could not find this services?

Thanks a lot. Have a nice day

**Comment by ishanVshah** [comment]
I am facing same error. what is the solution ?
